/**
 * Default CTI Report template used in Settings and as the server-side renderer
 * when a custom template is saved. {field} tokens are single values; {{BLOCK}}
 * tokens expand to generated markdown. Leave the editor at this default (saved
 * as empty) to use the built-in structured report.
 *
 * Field tokens:
 *   {date} {tlp} {report_id} {analyst_name} {org_name} {confidence} {severity}
 *   {summary} {affected_assets} {ioc_count} {technique_count}
 *   {threat_actor_name} {threat_actor_aliases} {threat_actor_motivation}
 *   {threat_actor_confidence} {initial_access} {motivation}
 *
 * Block tokens:
 *   {{SECTIONS}}          all enabled narrative sections, in Brief-Sections order
 *   {{SECTION:key}}       one specific section by key
 *   {{ATTACK_TABLE}}      ATT&CK technique summary table
 *   {{ATTACK_CHAIN}}      per-tactic technique detail
 *   {{IOC_TABLE}}         full IOC table
 *   {{EMAIL_IOCS}}        email/domain/URL indicators only
 *   {{AFFECTED_ASSETS_TABLE}}  affected-assets table
 *   {{THREAT_ACTOR}}      threat actor / malware summary
 *   {{CAMPAIGN_TIMELINE}} ordered kill-chain timeline
 */
export const DEFAULT_REPORT_TEMPLATE = `# Cyber Threat Intelligence Report
**TLP:** TLP:{tlp}
**Report ID:** {report_id}
**Date Published:** {date}
**Author/Team:** {analyst_name}
**Confidence Level:** {confidence}

---

# Threat Action

{summary}

---

# Threat Summary

**Severity:** {severity}
**Target Scope:** {affected_assets}
**Techniques:** {technique_count}
**IOCs:** {ioc_count}
**Threat Actor:** {threat_actor_name}

{{SECTIONS}}

---

# MITRE ATT&CK Mapping

{{ATTACK_TABLE}}

{{ATTACK_CHAIN}}

---

# Threat Actor / Malware Family

{{THREAT_ACTOR}}

---

# Campaign Timeline

{{CAMPAIGN_TIMELINE}}

---

# Affected Assets

{{AFFECTED_ASSETS_TABLE}}

---

# Indicators of Compromise (IOCs)

{{IOC_TABLE}}

---

*Generated by SNR — Signal to Noise | TLP:{tlp} | {date}*
`;
